config/routes.rb
Maps::Application.routes.draw do
  resources :spots
 
  root to: "welcome#index"
end

app/models/spot.rb
class Spot < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { render :json => Spot.all }
    end
  end

  def new
  end

  def create
    @spot = Spot.new(post_params)
    @spot.save

    redirect_to @spot
  end

  def show
    @spot = Spot.find(params[:id])
  end

  private
  def post_params
    params.require(:spot).permit(:title, :text, :long, :lat)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maps</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  <%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=true" %>
  <%= javascript_include_tag "http://hpneo.github.io/gmaps/gmaps.js" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spots/new.html.erb
<form id="geocoding_form">
  <div id="map"></div>
  <input type="text" id="address">Location</input>
  <input type="submit"></input>
</form>

<%= form_for :spot, url: spots_path  do |f| %>

  <p>
  <%= f.hidden_field :lat %>
  <%= f.hidden_field :long %>
  </p>

  <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
  </p>

  <p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
  </p>

  <p>
  <%= f.submit %>
  </p>
<% end %>

app/views/spots/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @spot.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @spot.text %>
</p>

<p>
  <strong>Location:</strong>
  <%= @spot.lat %>, <%= @spot.long %>
</p>

app/views/welcome/index.html.erb
<h1>Maps</h1>

<p>
<%= link_to 'new_spot' %>
</p>

<p>
<div id="frontmap"></div>
</p>